language: ruby
rvm:
  2.4.0
branches:
  only: master
script: bundle exec rake deploy
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: AgCwiTsuPqaXDVLbDpcoE3GaNKzh3rxBA9Vlw90rjj14VINuPBD28PgVqqxSVvPs7yvEWx9QXz9+dXNE5iQCfj+pOSJ8Zy7fHa7E/D571d+dFlMmWVNHCcVTFD9X453v3zo6emFrn8KT3lXQRoxBCV64MNr1ug/p7rY+29yS7XaIEbHqE/ahckZqbyN54j0l5b4y4KaE7lJmSLo0ySh9RoWwCnDfD5ZPutQWssVaoCTrzf4HqrA7DOJ7WNZQh651gWVKXUgzlHGPzKHKOylQlmG6mi5+bEwX87D8n7E5xDkveYaGTft3SRDIZN244SkWEC0wTQrnZv+RHRCLgOWu1L97aiI2XA2q4WhChm620xYrqaPX1XKECRiXm/MbIqPz4kWAu9lriKQdnqxpDrHAMtS/NkCnC7g44RLcgtMSjQh0aLhBHi1/f4q0CETsod0eVfMiplnVY9KBHQ9rW/8B62MAkdp0kEIdtoqsnigvFcGUN+INAobvUpYFGMNsQ+mPSzPgyRS+1a7R/WEoaeKq89SLPU8dSukje6MHhwg9KmjgZeC4eo0iL2uS5iqr36iCpbtloG/CmeYFnqGza3pXnhLl/C2DIAPcODNwqcBqnFlopZZBXL46RyWakS2SB2OEI12oYnGsItZUBKkA/DjCp6X2NhjoQ3bKnanQggqZuvo=
  - secure: WrtiGAM4/cTlsCCUK+h6zikqJdYLZNQCuYf6c7HcSvamEvg5ReDb8cu9BMSV8Mwyo1tE5C5AnaDYxHEZ+AkY6lJsqoY1gw/3aVS9NGsGJAqfHI1W33SXKpKyH0v7KJxR5+MIVdBznC1UpwqKT69BVlQSuLh674nhYEnvhu66RgwBjeJAicfmWObLWSiGdPdHf2lNrvbDNUv99p0tfXqD5Y1xFKCFiaRmB1L0f8+tEn7PvrzJKCnhPNaHC67+QHtoBQFb16ytlshmL+IirA1xDj5BmZmkbkPtT/2OPyiO/nT+frZLl+bZ5OfkhtbR5vfMm89mb5ej2fOs5kj/sTAzhsfi5rkKew7n6Q92xpehiHmsCUHKKZucoEJysY1Czca8sk08UGzuDErRr1nS6KZ1YHFToW2xCWMdok60NVWnJHQdaRu90BxXc+f0psLqJIUowREVbIIA6mJm4G4HbcjJW6DMkuBbs5DaPhpst90h25j0ThbIu/wrugf2DMdAW08awrDXAIPfKxfkJtvGT874/8Vk4ZrjTcY5nJEqJrH4MnGYPMlP1bEFMbhafRyq5uwJm1BaqRsPaO3atAV+/x+eB34iKmXQdHtNvja5PAuAxeo/umRJQvXyftiWrOq7m71P1AJHMS+lI40GfhF9YLnWJ6FTM/QH/LsjP5IoBqh7og8=
